# Generated by Django 3.1 on 2020-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='auction_winner_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
