# Generated by Django 3.1 on 2020-11-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201110_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.CharField(max_length=256),
        ),
    ]
